### PR TITLE
OOB Issue fixes

### PR DESCRIPTION
**Pull request by deepikabhavnani**
https://github.com/ARMmbed/qspif-blockdevice/issues/12 : Fix https://github.com/ARMmbed/qspif-blockdevice/commit/6895c396ace36055f4077289010c4fe90f5a78ae

https://github.com/ARMmbed/qspif-blockdevice/issues/11: Fix update the constructor arg https://github.com/ARMmbed/qspif-blockdevice/commit/9aeddbd3036867c124dd333a6a2274d85e625ebe

https://github.com/ARMmbed/qspif-blockdevice/issues/10: Fix https://github.com/ARMmbed/qspif-blockdevice/commit/f6bbd09512bb3c327c96bf1cfbaa5cedb1b7fbb7

### CODE REVIEW

**Comment by deepikabhavnani** [comment]
@maclobdell - Please review
@adbridge  - OOB branch was not present for this block device (I guess because it is not an example), hence adding fixes to master. Also,  maintainers have access to merge the pull request?

**Comment by cmonr** [comment]
@deepikabhavnani That would be a negative.

@geky might?

**Comment by deepikabhavnani** [comment]
Previous PR's are merged by @stevew817 @offirko

**Comment by geky** [comment]
Oh... Nope :laughing: 

@adbridge, maybe the maintainers should have admin privledges to the ARMmbed org? I don't blame the other guys here, it's easy to forget to add permissions on repos.

**Review by geky — APPROVED** [review]
Though thanks for this @deepikabhavnani :+1:  It looks good

**Comment by adbridge** [comment]
@geky I do have admin access ... ;-)

**Comment by stevew817** [comment]
I do have a comment on this PR. The pinouts have been added for a very small subset of targets supporting QSPI. This PR's description has a pretty exhaustive list over QSPI targets up and running in mbedOS 5.10: https://github.com/ARMmbed/mbed-os/pull/7817

CC @offirko @deepikabhavnani 

May I suggest changing the default pin settings to the defined QSPI_FLASH1_IO0..3, QSPI_FLASH1_SCK, QSPI_FLASH1_CSN?

**Comment by deepikabhavnani** [comment]
> May I suggest changing the default pin settings to the defined QSPI_FLASH1_IO0..3, QSPI_FLASH1_SCK, QSPI_FLASH1_CSN

Sure, thanks for input. Will add another PR to correct this

**Pull request merged**
