### PR TITLE
Give config option to enable trace and update example

### PR DESCRIPTION
**Pull request by deepikabhavnani**
Trace logs are added using mbed_trace library, but mechanism to enable them is missing. Also "Debug / error / Info" is added by mbed_trace library in log, hence not required in strings parsed to library.

### CODE REVIEW

**Comment by deepikabhavnani** [comment]
Output log with after enabling `MBED_CONF_MBED_TRACE_ENABLE`, We see failures in initialization as reported in issue https://github.com/ARMmbed/qspif-blockdevice/issues/15. This PR is to assist in debugging and would be helpful in future as well to debug code.

```
QSPI SFDP Flash Block Device example

[DBG ][QSPIF]: QSPIFBlockDevice csel: 75

[INFO][QSPIF]: _reset_flash_mem:

[DBG ][QSPIF]: Reading Status Register Success: value = 0x0

[DBG ][QSPIF]: Sending RSTEN Success

[DBG ][QSPIF]: Sending RST Success

[INFO][QSPIF]: Initialize flash memory OK

[INFO][QSPIF]: Init - verified SFDP Signature and version Successfully

[DBG ][QSPIF]: Number of Param Headers: 3

[DBG ][QSPIF]: Found Basic Param Table at Table: 1

[DBG ][QSPIF]: Detected Page Size: 256

[INFO][QSPIF]: Erase Type(A) 1 - Inst: 0xffh, Size: 4096

[INFO][QSPIF]: Erase Type 1 - Inst: 0x20h, Size: 4096

[INFO][QSPIF]: Erase Type(A) 2 - Inst: 0xffh, Size: 32768

[INFO][QSPIF]: Erase Type 2 - Inst: 0x52h, Size: 32768

[INFO][QSPIF]: Erase Type(A) 3 - Inst: 0xffh, Size: 65536

[INFO][QSPIF]: Erase Type 3 - Inst: 0xd8h, Size: 65536

[INFO][QSPIF]: Erase Type(A) 4 - Inst: 0xffh, Size: 1

[INFO][QSPIF]: Erase Type 4 - Inst: 0xffh, Size: 1

[DBG ][QSPIF]: /nRead Bus Mode set to 1-4-4, Instruction: 0xebh

[INFO][QSPIF]: Init - Setting Quad Enable

[DBG ][QSPIF]: Setting QE Bit, Bit 6 of Status Reg 1

[DBG ][QSPIF]: Reading Status Register Success: value = 0x0

[ERR ][QSPIF]: _set_write_enable failed

[ERR ][QSPIF]: Write Enabe failed

[ERR ][QSPIF]: Device supports Quad bus, but Quad Enable Failed

[ERR ][QSPIF]: Init - Parse Basic Param Table Failed
QSPI Flash init failed
```

**Comment by deepikabhavnani** [comment]
CC @geky

**Comment by geky** [comment]
This looks fine to me, though note we don't usually check return values on examples (leaving it as an exercise to the users, examples aren't tests).

**Comment by deepikabhavnani** [comment]
> This looks fine to me, though note we don't usually check return values on examples

We do https://github.com/ARMmbed/mbed-os-example-filesystem/blob/master/main.cpp#L49

**Comment by geky** [comment]
oh fair enough

**Review by geky — APPROVED** [review]

**Comment by deepikabhavnani** [comment]
@offirko - Please review.

**Comment by deepikabhavnani** [comment]
Closing as it was merged with next PR

**Pull request closed without merging**
